"""empty message

Revision ID: 28ced91da749
Revises: None
Create Date: 2016-07-12 22:06:11.523736

"""

# revision identifiers, used by Alembic.
revision = '28ced91da749'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
